{
  imports = [
    ./lazyvim
    ./niri
    ./noctalia
    ./umbriel
    ./catppuccin.nix
    ./entries.nix
    ./eza.nix
    ./fastfetch.nix
    ./fd.nix
    ./fzf.nix
    ./git.nix
    ./kitty.nix
    ./lazydocker.nix
    ./lazygit.nix
    ./navi.nix
    ./onlyoffice.nix
    ./programs.nix
    ./starship.nix
    ./themes.nix
    ./tldr.nix
    ./vesktop.nix
    ./yazi.nix
    ./zellij.nix
    ./zen.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
